export const INCREMENT_REQUESTED = 'INCREMENT_REQUESTED';
export const INCREMENT = 'INCREMENT';
export const DECREMENT_REQUESTED = 'DECREMENT_REQUESTED';
export const DECREMENT = 'DECREMENT';

export const CONTACT_FORM = 'CONTACT_FORM';
export const TEXT = 'TEXT';
export const EMAIL = 'EMAIL';
