export default {
	linear: t => t,
	easeInQuad: t => t * t,
	easeOutQuad: t => t * (2 - t),
	easeInOutQuad: t => (t < 0.5 ? 2 * t * t : -1 + ((4 - (2 * t)) * t)),
	easeInCubic: t => t * t * t,
	easeOutCubic: t => ((t - 1) ** 3) + 1,
	easeInOutCubic: t => (t < 0.5 ? 4 * t * t * t : (t - 1) * ((2 * t) - 2) * (((2 * t) - 2) + 1)),
	easeInQuart: t => t * t * t * t,
	easeOutQuart: t => 1 - ((t - 1) ** 4),
	easeInOutQuart: t => (t < 0.5 ? 8 * (t ** 4) : 1 - (8 * ((t - 1) ** 4))),
	easeInQuint: t => t ** 5,
	easeOutQuint: t => 1 + ((t - 1) ** 5),
	easeInOutQuint: t => (t < 0.5 ? 16 * (t ** 5) : 1 + (16 * ((t - 1) ** 5))),
};
